### ISSUE TITLE
Double-check social meta tags

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/demolitions#10]
Do one last check right before publication that Twitter card validates, the images are correct, the descriptions are descriptive, the copy has been edited, etc.

**Comment by ThomasThoren** [comment]
@myersnews , can you write the copy for Twitter and Facebook share buttons? You can click them now to see the dull placeholder text I have. Also please check that the image is okay. You can see it by clicking the Facebook icon. Twitter will populate the same image through the Twitter card, but you can't see it until you hit submit. You can confirm that it exists by entering the app URL here: https://cards-dev.twitter.com/validator

The current plan is to have the same message no matter where or when the user clicks on each icon (ex. same Facebook message for intro, story sidebar, photo sidebar and photo slideshow).

**Comment by myersnews** [comment]
Plan sounds good but I don’t see the share buttons. I’ll look again later in the day.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Oops, they're part of the shuffle going on with the mobile design. They'll be back soon.

**Comment by smyerslens** [comment]
revised after beatty's input:

Twitter: 
1000s of buildings were torn down after Katrina. Here's what stands on 150 of those lots now. #MissingHome 

Facebook: 
The city of New Orleans has granted 24,000 demolition permits since Katrina. The Lens and The Nation partnered to show you what happened to 150 of those properties. #MissingHome:  stories of change and stagnation.

**Comment by ThomasThoren** [comment]
Changed. Can you double-check that they look good for you?

**Comment by smyerslens** [comment]
## Still seeing old versions.

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Have you done a hard refresh? Everything is up to date on my end.

**Comment by smyerslens** [comment]
## Twitter works, Facebook is old.

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
I see the new one, so I'm closing this since it sounds like a caching issue and not a design problem.

**Comment by smyerslens** [comment]
## “user error,” in other words.

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
