### ISSUE TITLE
can we put street names on map? if not all, major streets?

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#19]

**Comment by ThomasThoren** [comment]
Here's a quick example I worked up in Mapbox Studio to show that it's possible. I'll adjust the font and level of detail before pushing the new style.

![mapbox-studio-streets](https://cloud.githubusercontent.com/assets/5692185/9429348/4e5f2088-4992-11e5-911c-71822435e822.png)

**Comment by smyerslens** [comment]
## Good. That outline style makes it a bit tough to read but it will work if we can’t fool with it.

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Here's a preview of what I just pushed. It might take a couple of minutes before you see the new tiles. I'll continue to work on the street name spacing.
![mapbox-studio-streets2](https://cloud.githubusercontent.com/assets/5692185/9429424/118dfa5a-4995-11e5-8cbb-07fb3b5564a4.png)

**Comment by smyerslens** [comment]
This is gone now.

**Comment by ThomasThoren** [comment]
What do you mean?

**Comment by smyerslens** [comment]
I don't see street names on the map.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Aug 26, 2015, at 9:08 AM, Thomas Thoren notifications@github.com wrote:

What do you mean?

**Comment by ThomasThoren** [comment]
All better.
