### ISSUE TITLE
photos above the fold

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#20]
let's work on getting more of the second photo above the fold on laptop and phone. 

to save space on the sidebar, should we swap the map and the text/photo column and put the nav buttons/title over the map?

we can also move share buttons up next to address.

i realize we can't get the entire second photo above but we can try for more.

we can also see how it works to put the caption below second photo, like you did before. that will save room between.

**Comment by ThomasThoren** [comment]
The fold isn't really something to be too concerned about. Many designers consider this a big misconception about web design. Most users are increasingly comfortable and willing to try scrolling, especially as mobile continues to grow.

I'll play around with the other ideas and see what I can do.

**Comment by ThomasThoren** [comment]
From #17:

"Move headline to the top so map isn't hidden on new page loads."

**Comment by smyerslens** [comment]
## I understand and agree that it’s not the biggest issue in general. But in this case we want people to draw the contrast between two images.

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
The two photos don't make the cut above the fold, but the current mobile design suggests scrolling down to the point where a user will be able to look at both photos. The initial screen shows the banner/nav bar, headline and half of the map, prompting to scroll down. Seeing the full map reveals half of the first photo, then followed by the second photo. There's always half of an element either up or down that tells users to try scrolling up or down, so I'm pretty content with the current layout.

Play around with it and let me know how it looks on your phone.

**Comment by ThomasThoren** [comment]
This has been addressed in other issues.
