### ISSUE TITLE
Where to put project credit, and who to include

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/demolitions#26]
Each person gets the byline/cutline for their own story/photo, of course. Should we do one big group byline for the main contributors at the start of the app? I'm thinking something like this:

![screen shot 2015-08-25 at 10 01 43 am](https://cloud.githubusercontent.com/assets/5692185/9470158/4e5d8fbe-4b10-11e5-94bf-e7108585006b.png)

**Comment by smyerslens** [comment]
## Content wise it’s fine though perhaps we can move it below the button to not interrupt the reader too much.

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by smyerslens** [comment]
Maybe "stories by..." to distinguish from the photography part.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Aug 25, 2015, at 10:02 AM, Thomas Thoren notifications@github.com
wrote:

Each person gets the byline/cutline for their own story/photo, of course.
Should we do one big group byline for the main contributors at the start of
the app? I'm thinking something like this:

[image: screen shot 2015-08-25 at 10 01 43 am]
https://cloud.githubusercontent.com/assets/5692185/9470158/4e5d8fbe-4b10-11e5-94bf-e7108585006b.png

—
Reply to this email directly or view it on GitHub
https://github.com/TheLens/demolitions/issues/26.

**Comment by ThomasThoren** [comment]
Putting it at the end of the intro for now.

![screen shot 2015-08-25 at 12 04 28 pm](https://cloud.githubusercontent.com/assets/5692185/9473651/88ba528a-4b21-11e5-8e7b-81e8febb96d8.png)
