### ISSUE TITLE
enable clicking on heat map to enter app

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#27]
does same thing as "explore" button.

**Comment by ThomasThoren** [comment]
This would remove any interactivity with the intro map. Is that acceptable? Either way, I'm not sure that this method of entry is very intuitive.

**Comment by smyerslens** [comment]
Right. Forget it.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Aug 25, 2015, at 12:24 PM, Thomas Thoren notifications@github.com
wrote:

This would remove any interactivity with the intro map. Is that acceptable?
Either way, I'm not sure that this method of entry is very intuitive.

**Comment by ThomasThoren** [comment]
Sounds good.
