### ISSUE TITLE
Tom to see if this credit line will fit

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#28]
For some photos:
The Historic New Orleans Collection, gift of FEMA

If not, it's 
THNOC, gift of FEMA

**Comment by smyerslens** [comment]
there are only 14 pix w/this photo credit.

**Comment by ThomasThoren** [comment]
It doesn't fit on mobile, but is fine otherwise. I could use the lengthier version if it fits and then swap in the abbreviation for small screens.

**Comment by smyerslens** [comment]
OK. I’ll add that credit line for all those pix.

## 

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
