### ISSUE TITLE
How to deal with photos for story sidebars?

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/demolitions#29]
My current layout plan is to go:

map/head (depending on mobile or desktop)
subhead
byline
lead image (old)
a couple of paragraphs of body text
second image (new)
the rest of the body text

Each story is limited to two stories in the sidebar. The rest will go in the slideshow.

This doesn't let the reader view the two images at the same time, but I think that's okay since the story sidebars are meant to emphasize the story more than the photos. This layout helps to give balance to the page and avoids grouping two images in a row, which might interrupt the flow of the story.

Thoughts, @myersnews ?

**Comment by smyerslens** [comment]
I knew I had missed an issue. Sorry I didn't respond. Current approach is good.

**Comment by ThomasThoren** [comment]
No problem. We talked about this over the phone.
