### ISSUE TITLE
Dates for photos

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/demolitions#30]
@myersnews Would you rather I round them all to the nearest month or stick with the most specific information we have for each photo?

**Comment by smyerslens** [comment]
Rather you stick with what we have but rounding will work fine too.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Aug 25, 2015, at 12:28 PM, Thomas Thoren notifications@github.com
wrote:

@myersnews https://github.com/myersnews Would you rather I round them all
to the nearest month or stick with the most specific information we have
for each photo?

—
Reply to this email directly or view it on GitHub
https://github.com/TheLens/demolitions/issues/30.

**Comment by ThomasThoren** [comment]
Sounds good to me! Less work is the best work.
