### ISSUE TITLE
Identify each FEMA/HNOC photo in spreadsheet using "Old Source" column

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/demolitions#31]

**Comment by smyerslens** [comment]
## Can you use the “old source” column?

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Yeah. I guess I meant, "Need to identify..." This is more of a to-do note.
