### ISSUE TITLE
photos not cropped properly

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#36]
I believe this was an issue with the label in the spreadsheet. http://projects.thelensnola.org/demolitions/#236-38-s-solomon-st

**Comment by smyerslens** [comment]
these addresses (unsure if there are others:
236-38 s. solomon
2516 acacia
2550 n prieur
1619 s liberty
738 voisin
1422-24 music

**Comment by ThomasThoren** [comment]
All fixed in the current batch going up to S3.
