### ISSUE TITLE
missing photos

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#39]
3519 washington: new photo (spreadsheet link looks ok)
3240 law: new (spreadsheet link appears ok)

1817 arts: shows broken image icon not the big red X (spreadsheet link appears ok)

2352-54 n roman: new - bad link, fixed in spreadsheet

**Comment by ThomasThoren** [comment]
1817 Arts and 3519 Washington fixed.

**Comment by ThomasThoren** [comment]
Closing in favor of #54 .
