### ISSUE TITLE
donate button next to share buttons?

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#43]
desktop view only b/c we're getting rid of them on mobile.

**Comment by ThomasThoren** [comment]
It's already too crowded in the banner. The social icons only fit in the large view. We'll have to think of another way to fit this into the app.

**Comment by smyerslens** [comment]
## What if we change the “about this project” to “support this project” and I change language on that page and we add a donate button that takes you to our donation page?

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
That works.

**Comment by smyerslens** [comment]
## OK give me a bit of time on that. You can change the link text whenever you want.

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Closing this since the link is fixed. #25 is still open to remind me to copy in your "About" text.
