### ISSUE TITLE
change mobile nav

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#46]
one line title bar with lens/nation logo next to Missing Home.
nav bar next (move from bottom)

consider scrolling title bar off and leaving nav bar on

**Comment by smyerslens** [comment]
Believe this has triggered odd behavior on desktop. When you click back or next, the title bar momentarily appears and then disappears.

**Comment by ThomasThoren** [comment]
I still haven't been able to figure this out, but at least now the address won't hide under the nav bar.

**Comment by ThomasThoren** [comment]
This should be straightened out now. The banner and nav bar will both be visible until the user scrolls down, when the nav bar sticks to the top.
