### ISSUE TITLE
odd nav bar behavior on iphone

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#48]
may not be anything you can do about this:

scroll down on a property. hit next. phone unhides the browser chrome and you have to hit next again. doesn’t happen if you didn’t scroll.

**Comment by ThomasThoren** [comment]
I'm not sure I follow what you're describing. The nav bar is reworked since you posted this, so it's possible that the new design effectively fixes this.

**Comment by ThomasThoren** [comment]
Can you elaborate on this, @myersnews ?

**Comment by smyerslens** [comment]
Fixed in new design.
