### ISSUE TITLE
next button on stories

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#49]
seems to just cycle through stories when you're in a story and hit next, rather than all properties. is that the behavior we want?

**Comment by ThomasThoren** [comment]
This isn't supposed to happen. Can you try to recreate it?

**Comment by smyerslens** [comment]
home page, hit explore the city. choose "notable church flattened." from there it goes down the list of stories and then goes to photos only. same behavior with:
renovation saved
swapped lot

**Comment by ThomasThoren** [comment]
This was worked out in #62.
