### ISSUE TITLE
Map outline around New Orleans

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/demolitions#5]

**Comment by ThomasThoren** [comment]
Current version:

![screen shot 2015-08-24 at 10 40 51 am](https://cloud.githubusercontent.com/assets/5692185/9444479/a2c67a12-4a4c-11e5-997b-7922fee10616.png)

**Comment by smyerslens** [comment]
## That’s good.

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
