### ISSUE TITLE
photo issues

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#54]
Let's use this for anything related to the incorrect photo displaying.

2119 Painters: First photo should be old photo but it's showing detail. First line in app is correct. It's showing third photo. I just had a problem viewing the photo on the 3rd row so I downloaded and reuploaded. Let's see if this is fixed when you re-run script.

**Comment by ThomasThoren** [comment]
3240 law: new (spreadsheet link appears ok)
2352-54 n roman: new - bad link, fixed in spreadsheet

**Comment by ThomasThoren** [comment]
All photos are fixed in the app. Closing this for now, but you can reopen it if you see any other problems.

**Comment by ThomasThoren** [comment]
4651 Western photos are missing. They're toward the end of the spreadsheet, so I'm guessing they're new since I last ran the script.

**Comment by smyerslens** [comment]
## odd. i think i added them yesterday.

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
I go long times between uploading photos since I can only do it at home. I see these on my laptop, so I only need to upload them.

**Comment by smyerslens** [comment]
Missing new photo for 6115-17 Burgundy, taken wed am:
https://drive.google.com/a/thelensnola.org/file/d/0B2doKNlGQ8nJNW5YWEEtQ0xuUFE/view

**Comment by smyerslens** [comment]
broken image link on new photo for 3129 palmyra

**Comment by smyerslens** [comment]
5523 woodlawn-new

**Comment by ThomasThoren** [comment]
All are up and working now.
