### ISSUE TITLE
use this for main image

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#56]
https://drive.google.com/a/thelensnola.org/file/d/0BxdCNQlr6OmWd0VzSlcxbkU3eWM/view

**Comment by ThomasThoren** [comment]
Karen is out taking an image for this.

**Comment by ThomasThoren** [comment]
A copy is uploaded in a temporary space for viewing purposes. I'll swap in the permanent link that is created as part of the processing script once it's online.

**Comment by ThomasThoren** [comment]
Permanent location URL swapped in.
