### ISSUE TITLE
subhead hovering in space

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#59]
See if you can visually anchor it somewhere. The italicized test may be contributing to a sense of it being an afterthought. maybe use same font as body text but boldface?

**Comment by ThomasThoren** [comment]
Removed the italics and shifted down more toward the body text. Let me know what you think.

**Comment by smyerslens** [comment]
## that works better.

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
