### ISSUE TITLE
Photo caption format: date on left, credit on right.

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/demolitions#6]

**Comment by ThomasThoren** [comment]
This works fine for when there isn't a caption, such as the photo gallery sidebars. What do you want it to look like for the story sidebars, @myersnews? Those will only have a single picture, so the caption will need to be a part of the cutline.

I'm assuming something like this, either with or without the border to create a buffer between the image and the body text:

![screen shot 2015-08-24 at 11 21 39 am](https://cloud.githubusercontent.com/assets/5692185/9445558/5da02bb2-4a52-11e5-832a-4f5a6c1bbe89.png)

The same thing will be true for the gallery slideshow. Each photo will have date, (repeated) caption and credit.

**Comment by smyerslens** [comment]
## I agree that a horizontal line will help visually separate them. However story sidebars also will have two photo, then and now. (We’re dealing with a problem on one but in general that’s the plan.0

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
