### ISSUE TITLE
change logic for how "next/prev" buttons work

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#62]
all the narratives are in a group. i don't think we'll get people to read them that way.

**Comment by smyerslens** [comment]
I see, the app just goes down the list, doesn't it? because the list is in numerical order, the app is too.

**Comment by ThomasThoren** [comment]
There is no logic. The buttons simply go up and down in the spreadsheet's addresses. The stories are bunched toward the end, so it looks as if it's selecting more stories, but it isn't.

If we sort the spreadsheet alphabetically, it should create a more spread-out look.

**Comment by smyerslens** [comment]
yeah i was just going to say that i figured that out. I'm going to just manually move those stories throughout. i don't want to risk putting a new photo on first row of an address.
