### ISSUE TITLE
Increase cache age for S3 assets after all bugs are fixed, styles smoothed out

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/demolitions#65]
Leaving no cache on JS/CSS files for now so I can quickly update anything that needs it. Once they are final, I'll increase the cache on the files.

**Comment by smyerslens** [comment]
## time for that?

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
I need to keep the cache off so I can push updates and ensure that users see them. I'll turn on the cache once I know everything is kosher.

**Comment by smyerslens** [comment]
Ok

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Aug 27, 2015, at 10:40 AM, Thomas Thoren notifications@github.com
wrote:

I need to keep the cache off so I can push updates and ensure that users
see them. I'll turn on the cache once I know everything is kosher.
